services:
  - type: web
    name: diploma-fastapi
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        sync: false
      - key: JWT_EXPIRE_MINUTES
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        sync: false
